  name: Deploy Frontend
  on:
    push:
      branches:
        - master

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Build docker image
          run: docker build -t bigyellowhammer/docker-react .
        
        - name: Run tests
          run: docker run -e CI=true bigyellowhammer/docker-react npm run test

        - name: Generate deployment package
          run: zip -r deploy.zip . -x '*.git*'
        
        - name: Deploy to AWS Elasticbeanstalk
          uses: einaregilsson/beanstalk-deploy@v21
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
            application_name: FirstReactApp
            environment_name: FirstReactApp-env
            existing_bucket_name: elasticbeanstalk-us-east-1-495531827909
            region: us-east-1
            version_label: ${{ github.sha}}
            deployment_package: deploy.zip